In [2]:
import pandas as pd
import numpy as np

dataset = pd.read_csv("LowestFares.csv") #Read in dataset

C:\Users\Karth\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,1,2,3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
dataset.head()

,Origin,Destination,FlightDate,FlightType,FareType,DollarFare,DollarTax,TotalAmount,PointsFare,PointsTax,IsDomesticRoute,IsPrivateFare
0,SFO,BOS,11/29/2017 14:24,NONSTOP,LOWEST,683.20,60.87,744.07,0.0,0.0,1.0,0.0
1,SFO,BOS,11/29/2017 14:24,NONSTOP,POINTS,499.20,48.04,547.24,42200.0,5.6,1.0,1.0
2,LGB,SEA,11/29/2017 14:32,NONSTOP,LOWEST,164.19,24.66,188.85,0.0,0.0,1.0,0.0
3,LGB,SEA,11/29/2017 14:32,NONSTOP,POINTS,164.19,24.66,188.85,11200.0,5.6,1.0,0.0
4,LAS,LGB,11/29/2017 14:59,NONSTOP,LOWEST,40.20,16.01,56.21,0.0,0.0,1.0,0.0

For Money Based Flights:

In [4]:
dMoney = dataset[dataset['FareType'] == 'LOWEST'] #Separates by FareType to only Money Based Fares
dMoney.head()

,Origin,Destination,FlightDate,FlightType,FareType,DollarFare,DollarTax,TotalAmount,PointsFare,PointsTax,IsDomesticRoute,IsPrivateFare
0,SFO,BOS,11/29/2017 14:24,NONSTOP,LOWEST,683.20,60.87,744.07,0.0,0.0,1.0,0.0
2,LGB,SEA,11/29/2017 14:32,NONSTOP,LOWEST,164.19,24.66,188.85,0.0,0.0,1.0,0.0
4,LAS,LGB,11/29/2017 14:59,NONSTOP,LOWEST,40.20,16.01,56.21,0.0,0.0,1.0,0.0
6,LAS,BOS,11/29/2017 15:03,NONSTOP,LOWEST,414.98,42.16,457.14,0.0,0.0,1.0,0.0
8,LGB,JFK,11/29/2017 15:04,NONSTOP,LOWEST,471.20,46.08,517.28,0.0,0.0,1.0,0.0

In [5]:
originMoney = np.array(dMoney['Origin'])
np.unique(originMoney)   #Finds all unique Origins

array(['ABQ', 'ACK', 'ALB', 'ANU', 'ATL', 'AUA', 'AUS', 'BDA', 'BDL',
       'BGI', 'BNA', 'BOG', 'BOS', 'BQN', 'BTV', 'BUF', 'BUR', 'BWI',
       'CHS', 'CLE', 'CLT', 'CMW', 'CTG', 'CUN', 'CUR', 'DAB', 'DCA',
       'DEN', 'DFW', 'DTW', 'EWR', 'FLL', 'GCM', 'GND', 'HAV', 'HOG',
       'HOU', 'HPN', 'IAD', 'JAX', 'JFK', 'KIN', 'LAS', 'LAX', 'LGA',
       'LGB', 'LIM', 'LIR', 'LRM', 'MBJ', 'MCO', 'MDE', 'MEX', 'MSY',
       'MVY', 'NAS', 'OAK', 'ORD', 'ORH', 'PAP', 'PBI', 'PDX', 'PHL',
       'PHX', 'PIT', 'PLS', 'POP', 'POS', 'PSE', 'PSP', 'PUJ', 'PVD',
       'PWM', 'RDU', 'RIC', 'RNO', 'ROC', 'RSW', 'SAN', 'SAV', 'SDQ',
       'SEA', 'SFO', 'SJC', 'SJO', 'SJU', 'SLC', 'SMF', 'SNU', 'SRQ',
       'STI', 'STT', 'STX', 'SWF', 'SXM', 'SYR', 'TPA', 'UIO', 'UVF'], dtype=object)

In [6]:
destinationMoney = np.array(dMoney['Destination'])
np.unique(destinationMoney)    #Finds all unique Destinations

array(['ABQ', 'ACK', 'ALB', 'ANU', 'ATL', 'AUA', 'AUS', 'BDA', 'BDL',
       'BGI', 'BNA', 'BOG', 'BOS', 'BQN', 'BTV', 'BUF', 'BUR', 'BWI',
       'CHS', 'CLE', 'CLT', 'CMW', 'CTG', 'CUN', 'CUR', 'DAB', 'DCA',
       'DEN', 'DFW', 'DTW', 'EWR', 'FLL', 'GCM', 'GND', 'HAV', 'HOG',
       'HOU', 'HPN', 'IAD', 'JAX', 'JFK', 'KIN', 'LAS', 'LAX', 'LGA',
       'LGB', 'LIM', 'LIR', 'LRM', 'MBJ', 'MCO', 'MDE', 'MEX', 'MSY',
       'MVY', 'NAS', 'OAK', 'ORD', 'ORH', 'PAP', 'PBI', 'PDX', 'PHL',
       'PHX', 'PIT', 'PLS', 'POP', 'POS', 'PSE', 'PSP', 'PUJ', 'PVD',
       'PWM', 'RDU', 'RIC', 'RNO', 'ROC', 'RSW', 'SAN', 'SAV', 'SDQ',
       'SEA', 'SFO', 'SJC', 'SJO', 'SJU', 'SLC', 'SMF', 'SNU', 'SRQ',
       'STI', 'STT', 'STX', 'SWF', 'SXM', 'SYR', 'TPA', 'UIO', 'UVF'], dtype=object)

In [7]:
temp = np.array(dMoney['FlightDate'])
settingMoney = temp.tolist()
dateMoney = [i.split(' ', 1)[0] for i in settingMoney] #Splits the FlightDate Column to just get the Date
uniqueDateMoney = []
for i in dateMoney:
    if i not in uniqueDateMoney: #Finds the unique dates of each of the flights
        uniqueDateMoney.append(i)
print(uniqueDateMoney) 

timeMoney = [i.split(' ', 1)[1] for i in settingMoney] #Splits the FlightDate Column to just get the Time
uniqueTimeMoney = []
for i in timeMoney:
    if i not in uniqueTimeMoney: #Finds the unique times of each of the flights
        uniqueTimeMoney.append(i)
sortedTimeMoney = sorted(uniqueTimeMoney)
print(sortedTimeMoney)

['11/29/2017', '11/30/2017', '12/1/2017', '12/2/2017', '12/3/2017', '12/4/2017', '12/5/2017', '12/6/2017', '12/7/2017', '12/8/2017', '12/9/2017', '12/10/2017', '12/11/2017', '12/12/2017', '12/13/2017', '12/14/2017', '12/15/2017', '12/16/2017', '12/17/2017', '12/18/2017', '12/19/2017', '12/20/2017', '12/21/2017', '12/22/2017', '12/23/2017', '12/24/2017', '12/25/2017', '12/26/2017', '12/27/2017', '12/28/2017', '12/29/2017', '12/30/2017', '12/31/2017', '1/1/2018', '1/2/2018', '1/3/2018', '1/4/2018', '1/5/2018', '1/6/2018', '1/7/2018', '1/8/2018', '1/9/2018', '1/10/2018', '1/11/2018', '1/12/2018', '1/13/2018', '1/14/2018', '1/15/2018', '1/16/2018', '1/17/2018', '1/18/2018', '1/19/2018', '1/20/2018', '1/21/2018', '1/22/2018', '1/23/2018', '1/24/2018', '1/25/2018', '1/26/2018', '1/27/2018', '1/28/2018', '1/29/2018', '1/30/2018', '1/31/2018', '2/1/2018', '2/2/2018', '2/3/2018', '2/4/2018', '2/5/2018', '2/6/2018', '2/7/2018', '2/8/2018', '2/9/2018', '2/10/2018', '2/11/2018', '2/12/2018', '2/13/2018', '2/14/2018', '2/15/2018', '2/16/2018', '2/17/2018', '2/18/2018', '2/19/2018', '2/20/2018', '2/21/2018', '2/22/2018', '2/23/2018', '2/24/2018', '2/25/2018', '2/26/2018', '2/27/2018', '2/28/2018', '3/1/2018', '3/2/2018', '3/3/2018', '3/4/2018', '3/5/2018', '3/6/2018', '3/7/2018', '3/8/2018', '3/9/2018', '3/10/2018', '3/11/2018', '3/12/2018', '3/13/2018', '3/14/2018', '3/15/2018', '3/16/2018', '3/17/2018', '3/18/2018', '3/19/2018', '3/20/2018', '3/21/2018', '3/22/2018', '3/23/2018', '3/24/2018', '3/25/2018', '3/26/2018', '3/27/2018', '3/28/2018', '3/29/2018', '3/30/2018', '3/31/2018']
['0:30', '0:40', '0:49', '0:59', '10:00', '10:01', '10:02', '10:03', '10:04', '10:05', '10:06', '10:07', '10:08', '10:09', '10:10', '10:11', '10:12', '10:13', '10:14', '10:15', '10:16', '10:17', '10:18', '10:19', '10:20', '10:21', '10:22', '10:23', '10:24', '10:25', '10:26', '10:27', '10:28', '10:29', '10:30', '10:31', '10:32', '10:33', '10:34', '10:35', '10:36', '10:37', '10:38', '10:39', '10:40', '10:41', '10:42', '10:43', '10:44', '10:45', '10:46', '10:47', '10:48', '10:49', '10:50', '10:51', '10:52', '10:53', '10:54', '10:55', '10:56', '10:57', '10:58', '10:59', '11:00', '11:01', '11:02', '11:03', '11:04', '11:05', '11:06', '11:07', '11:08', '11:09', '11:10', '11:11', '11:12', '11:13', '11:15', '11:16', '11:17', '11:18', '11:19', '11:20', '11:21', '11:22', '11:23', '11:24', '11:25', '11:26', '11:27', '11:28', '11:29', '11:30', '11:31', '11:32', '11:33', '11:34', '11:35', '11:36', '11:37', '11:38', '11:39', '11:40', '11:41', '11:42', '11:43', '11:44', '11:45', '11:46', '11:47', '11:48', '11:49', '11:50', '11:51', '11:52', '11:53', '11:54', '11:55', '11:56', '11:57', '11:58', '11:59', '12:00', '12:01', '12:02', '12:03', '12:04', '12:05', '12:06', '12:07', '12:08', '12:09', '12:10', '12:11', '12:12', '12:13', '12:14', '12:15', '12:16', '12:17', '12:18', '12:19', '12:20', '12:21', '12:22', '12:23', '12:24', '12:25', '12:26', '12:27', '12:29', '12:30', '12:31', '12:32', '12:33', '12:34', '12:35', '12:36', '12:37', '12:38', '12:39', '12:40', '12:41', '12:42', '12:43', '12:44', '12:45', '12:46', '12:47', '12:48', '12:49', '12:50', '12:51', '12:52', '12:53', '12:54', '12:55', '12:56', '12:57', '12:58', '12:59', '13:00', '13:01', '13:02', '13:03', '13:04', '13:05', '13:06', '13:07', '13:08', '13:09', '13:10', '13:11', '13:12', '13:13', '13:14', '13:15', '13:16', '13:17', '13:18', '13:19', '13:20', '13:21', '13:22', '13:23', '13:24', '13:25', '13:26', '13:27', '13:28', '13:29', '13:30', '13:31', '13:32', '13:33', '13:34', '13:35', '13:36', '13:37', '13:38', '13:39', '13:40', '13:41', '13:42', '13:43', '13:44', '13:45', '13:46', '13:47', '13:48', '13:49', '13:50', '13:51', '13:52', '13:53', '13:54', '13:55', '13:56', '13:57', '13:58', '13:59', '14:00', '14:01', '14:02', '14:03', '14:04', '14:05', '14:06', '14:07', '14:08', '14:09', '14:10', '14:11', '14:12', '14:13', '14:14', '14:15', '14:16', '14:17', '14:18', '14:19', '14:20', '14:21', '14:22', '14:23', '14:24', '14:25', '14:27', '14:28', '14:29', '14:30', '14:31', '14:32', '14:33', '14:34', '14:35', '14:36', '14:37', '14:38', '14:39', '14:40', '14:41', '14:42', '14:43', '14:44', '14:45', '14:46', '14:47', '14:48', '14:49', '14:50', '14:51', '14:52', '14:53', '14:54', '14:55', '14:56', '14:57', '14:58', '14:59', '15:00', '15:01', '15:02', '15:03', '15:04', '15:05', '15:06', '15:07', '15:08', '15:09', '15:10', '15:11', '15:12', '15:14', '15:15', '15:16', '15:17', '15:18', '15:19', '15:20', '15:21', '15:22', '15:23', '15:24', '15:25', '15:26', '15:27', '15:28', '15:29', '15:30', '15:31', '15:32', '15:34', '15:35', '15:36', '15:37', '15:38', '15:39', '15:40', '15:41', '15:42', '15:43', '15:44', '15:45', '15:46', '15:47', '15:48', '15:49', '15:50', '15:51', '15:52', '15:53', '15:54', '15:55', '15:56', '15:57', '15:58', '15:59', '16:00', '16:01', '16:02', '16:03', '16:04', '16:05', '16:06', '16:07', '16:08', '16:09', '16:10', '16:11', '16:12', '16:13', '16:14', '16:15', '16:16', '16:17', '16:18', '16:19', '16:20', '16:21', '16:22', '16:23', '16:24', '16:25', '16:26', '16:27', '16:28', '16:29', '16:30', '16:31', '16:32', '16:34', '16:35', '16:36', '16:38', '16:39', '16:40', '16:41', '16:42', '16:43', '16:44', '16:45', '16:46', '16:47', '16:48', '16:49', '16:50', '16:51', '16:52', '16:53', '16:54', '16:55', '16:56', '16:57', '16:58', '16:59', '17:00', '17:01', '17:02', '17:03', '17:04', '17:05', '17:06', '17:07', '17:08', '17:09', '17:10', '17:11', '17:12', '17:13', '17:14', '17:15', '17:16', '17:17', '17:18', '17:19', '17:20', '17:21', '17:22', '17:23', '17:24', '17:25', '17:27', '17:28', '17:29', '17:30', '17:31', '17:32', '17:33', '17:34', '17:35', '17:36', '17:38', '17:39', '17:40', '17:41', '17:42', '17:43', '17:44', '17:45', '17:46', '17:47', '17:48', '17:49', '17:50', '17:51', '17:52', '17:53', '17:54', '17:55', '17:56', '17:57', '17:58', '17:59', '18:00', '18:01', '18:02', '18:03', '18:04', '18:05', '18:06', '18:07', '18:08', '18:09', '18:10', '18:11', '18:12', '18:13', '18:14', '18:15', '18:16', '18:17', '18:18', '18:19', '18:20', '18:21', '18:22', '18:23', '18:24', '18:25', '18:26', '18:27', '18:28', '18:29', '18:30', '18:31', '18:32', '18:33', '18:34', '18:35', '18:36', '18:37', '18:38', '18:39', '18:40', '18:41', '18:42', '18:43', '18:44', '18:45', '18:46', '18:47', '18:48', '18:49', '18:50', '18:51', '18:52', '18:53', '18:54', '18:55', '18:56', '18:57', '18:58', '18:59', '19:00', '19:01', '19:02', '19:03', '19:04', '19:05', '19:06', '19:07', '19:08', '19:09', '19:10', '19:11', '19:12', '19:13', '19:14', '19:15', '19:16', '19:17', '19:18', '19:19', '19:20', '19:21', '19:23', '19:24', '19:25', '19:26', '19:27', '19:28', '19:29', '19:30', '19:31', '19:32', '19:33', '19:34', '19:35', '19:36', '19:37', '19:38', '19:39', '19:40', '19:41', '19:42', '19:43', '19:44', '19:45', '19:46', '19:47', '19:48', '19:49', '19:50', '19:52', '19:53', '19:54', '19:55', '19:57', '19:58', '19:59', '1:13', '1:25', '1:28', '1:30', '1:40', '1:45', '1:46', '1:52', '1:57', '1:59', '20:00', '20:01', '20:02', '20:03', '20:04', '20:05', '20:06', '20:07', '20:08', '20:09', '20:10', '20:11', '20:12', '20:13', '20:14', '20:15', '20:16', '20:17', '20:18', '20:19', '20:20', '20:21', '20:22', '20:23', '20:24', '20:25', '20:26', '20:27', '20:28', '20:29', '20:30', '20:31', '20:32', '20:33', '20:34', '20:35', '20:36', '20:37', '20:38', '20:39', '20:40', '20:41', '20:42', '20:43', '20:45', '20:46', '20:47', '20:48', '20:49', '20:50', '20:51', '20:52', '20:53', '20:54', '20:55', '20:56', '20:57', '20:58', '20:59', '21:00', '21:01', '21:02', '21:03', '21:04', '21:05', '21:06', '21:07', '21:08', '21:09', '21:10', '21:11', '21:12', '21:13', '21:14', '21:15', '21:16', '21:17', '21:18', '21:19', '21:20', '21:21', '21:22', '21:23', '21:24', '21:25', '21:26', '21:27', '21:28', '21:29', '21:30', '21:31', '21:32', '21:33', '21:34', '21:35', '21:37', '21:38', '21:39', '21:40', '21:41', '21:42', '21:43', '21:44', '21:45', '21:46', '21:47', '21:48', '21:49', '21:50', '21:51', '21:52', '21:54', '21:55', '21:56', '21:57', '21:58', '21:59', '22:00', '22:01', '22:02', '22:03', '22:05', '22:06', '22:07', '22:08', '22:09', '22:10', '22:11', '22:12', '22:13', '22:15', '22:16', '22:17', '22:18', '22:19', '22:20', '22:22', '22:23', '22:24', '22:25', '22:26', '22:27', '22:28', '22:29', '22:30', '22:31', '22:32', '22:33', '22:34', '22:35', '22:36', '22:37', '22:38', '22:39', '22:40', '22:41', '22:42', '22:43', '22:44', '22:45', '22:46', '22:48', '22:49', '22:50', '22:51', '22:52', '22:54', '22:55', '22:56', '22:57', '22:58', '22:59', '23:00', '23:02', '23:05', '23:06', '23:07', '23:08', '23:10', '23:11', '23:12', '23:13', '23:14', '23:15', '23:16', '23:17', '23:18', '23:20', '23:22', '23:23', '23:25', '23:26', '23:27', '23:28', '23:29', '23:30', '23:31', '23:33', '23:35', '23:36', '23:37', '23:38', '23:39', '23:40', '23:41', '23:42', '23:43', '23:44', '23:45', '23:46', '23:48', '23:49', '23:50', '23:51', '23:52', '23:53', '23:54', '23:55', '23:56', '23:57', '23:58', '23:59', '2:09', '2:28', '2:30', '2:32', '2:35', '2:38', '2:39', '2:40', '2:45', '2:46', '2:47', '2:48', '2:50', '2:55', '2:57', '2:58', '3:00', '3:06', '3:07', '3:08', '3:17', '3:20', '3:22', '3:24', '3:26', '3:27', '3:30', '3:31', '3:34', '3:36', '3:38', '3:39', '3:40', '3:41', '3:43', '3:44', '3:48', '4:00', '4:05', '4:06', '4:07', '4:08', '4:11', '4:13', '4:14', '4:15', '4:18', '4:21', '4:24', '4:27', '4:28', '4:30', '4:32', '4:35', '4:36', '4:39', '4:40', '4:41', '4:48', '4:49', '4:51', '4:57', '4:58', '4:59', '5:00', '5:01', '5:02', '5:03', '5:06', '5:07', '5:08', '5:15', '5:18', '5:20', '5:24', '5:25', '5:30', '5:32', '5:33', '5:34', '5:35', '5:36', '5:37', '5:38', '5:39', '5:40', '5:43', '5:45', '5:46', '5:47', '5:50', '5:52', '5:54', '5:57', '5:58', '5:59', '6:00', '6:01', '6:02', '6:03', '6:04', '6:05', '6:06', '6:07', '6:08', '6:09', '6:10', '6:11', '6:12', '6:13', '6:14', '6:15', '6:16', '6:17', '6:18', '6:20', '6:21', '6:22', '6:23', '6:24', '6:25', '6:26', '6:28', '6:29', '6:30', '6:32', '6:33', '6:34', '6:35', '6:36', '6:37', '6:38', '6:39', '6:40', '6:41', '6:42', '6:43', '6:44', '6:45', '6:46', '6:48', '6:49', '6:50', '6:51', '6:52', '6:53', '6:54', '6:55', '6:56', '6:57', '6:58', '6:59', '7:00', '7:01', '7:02', '7:03', '7:04', '7:05', '7:06', '7:07', '7:08', '7:09', '7:10', '7:11', '7:12', '7:13', '7:14', '7:15', '7:16', '7:17', '7:18', '7:19', '7:20', '7:21', '7:22', '7:23', '7:24', '7:25', '7:26', '7:27', '7:28', '7:29', '7:30', '7:31', '7:32', '7:33', '7:34', '7:35', '7:36', '7:37', '7:38', '7:39', '7:40', '7:41', '7:42', '7:43', '7:44', '7:45', '7:47', '7:48', '7:49', '7:50', '7:51', '7:52', '7:53', '7:54', '7:55', '7:56', '7:57', '7:58', '7:59', '8:00', '8:01', '8:02', '8:03', '8:04', '8:05', '8:06', '8:07', '8:08', '8:09', '8:10', '8:11', '8:12', '8:13', '8:15', '8:16', '8:17', '8:18', '8:19', '8:20', '8:21', '8:22', '8:23', '8:24', '8:25', '8:26', '8:27', '8:28', '8:29', '8:30', '8:31', '8:32', '8:33', '8:34', '8:35', '8:36', '8:37', '8:38', '8:39', '8:40', '8:41', '8:42', '8:43', '8:44', '8:45', '8:46', '8:47', '8:48', '8:49', '8:50', '8:51', '8:52', '8:53', '8:54', '8:55', '8:56', '8:57', '8:58', '8:59', '9:00', '9:01', '9:02', '9:03', '9:04', '9:05', '9:06', '9:07', '9:08', '9:09', '9:10', '9:11', '9:12', '9:13', '9:15', '9:16', '9:17', '9:19', '9:20', '9:21', '9:22', '9:23', '9:24', '9:25', '9:26', '9:27', '9:28', '9:29', '9:30', '9:31', '9:32', '9:33', '9:34', '9:35', '9:36', '9:38', '9:39', '9:40', '9:41', '9:42', '9:43', '9:44', '9:45', '9:46', '9:47', '9:48', '9:49', '9:50', '9:51', '9:52', '9:53', '9:54', '9:55', '9:56', '9:57', '9:58', '9:59']

In [8]:
amountMoney = np.array(dMoney['TotalAmount'])
sortedMoney = np.sort(amountMoney) #Sorts data set by the total cost of the flight, cheapest to most expensive
print(sortedMoney)

[   46.59    46.59    46.59 ...,  1445.32  1491.32  1541.12]

For Points Based Flights:

In [9]:
dPoints = dataset[dataset['FareType'] == 'POINTS'] #Separates by FareType to only Points Based Fares
dPoints.head()

,Origin,Destination,FlightDate,FlightType,FareType,DollarFare,DollarTax,TotalAmount,PointsFare,PointsTax,IsDomesticRoute,IsPrivateFare
1,SFO,BOS,11/29/2017 14:24,NONSTOP,POINTS,499.20,48.04,547.24,42200.0,5.6,1.0,1.0
3,LGB,SEA,11/29/2017 14:32,NONSTOP,POINTS,164.19,24.66,188.85,11200.0,5.6,1.0,0.0
5,LAS,LGB,11/29/2017 14:59,NONSTOP,POINTS,40.20,16.01,56.21,2000.0,5.6,1.0,0.0
7,LAS,BOS,11/29/2017 15:03,NONSTOP,POINTS,414.98,42.16,457.14,34900.0,5.6,1.0,0.0
9,LGB,JFK,11/29/2017 15:04,NONSTOP,POINTS,471.20,46.08,517.28,43600.0,5.6,1.0,0.0

In [10]:
originPoints = np.array(dPoints['Origin']) 
np.unique(originPoints)    #Finds all unique Origins

array(['ABQ', 'ALB', 'ANU', 'ATL', 'AUA', 'AUS', 'BDA', 'BDL', 'BGI',
       'BNA', 'BOG', 'BOS', 'BQN', 'BTV', 'BUF', 'BUR', 'BWI', 'CHS',
       'CLE', 'CLT', 'CMW', 'CTG', 'CUN', 'CUR', 'DAB', 'DCA', 'DEN',
       'DFW', 'DTW', 'EWR', 'FLL', 'GCM', 'GND', 'HAV', 'HOG', 'HOU',
       'HPN', 'IAD', 'JAX', 'JFK', 'KIN', 'LAS', 'LAX', 'LGA', 'LGB',
       'LIM', 'LIR', 'LRM', 'MBJ', 'MCO', 'MDE', 'MEX', 'MSY', 'NAS',
       'OAK', 'ORD', 'ORH', 'PAP', 'PBI', 'PDX', 'PHL', 'PHX', 'PIT',
       'PLS', 'POP', 'POS', 'PSE', 'PSP', 'PUJ', 'PVD', 'PWM', 'RDU',
       'RIC', 'RNO', 'ROC', 'RSW', 'SAN', 'SAV', 'SDQ', 'SEA', 'SFO',
       'SJC', 'SJO', 'SJU', 'SLC', 'SMF', 'SNU', 'SRQ', 'STI', 'STT',
       'STX', 'SWF', 'SXM', 'SYR', 'TPA', 'UIO', 'UVF'], dtype=object)

In [11]:
destinationPoints = np.array(dPoints['Destination'])
np.unique(destinationPoints)  #Finds all unique Destinations

array(['ABQ', 'ALB', 'ANU', 'ATL', 'AUA', 'AUS', 'BDA', 'BDL', 'BGI',
       'BNA', 'BOG', 'BOS', 'BQN', 'BTV', 'BUF', 'BUR', 'BWI', 'CHS',
       'CLE', 'CLT', 'CMW', 'CTG', 'CUN', 'CUR', 'DAB', 'DCA', 'DEN',
       'DFW', 'DTW', 'EWR', 'FLL', 'GCM', 'GND', 'HAV', 'HOG', 'HOU',
       'HPN', 'IAD', 'JAX', 'JFK', 'KIN', 'LAS', 'LAX', 'LGA', 'LGB',
       'LIM', 'LIR', 'LRM', 'MBJ', 'MCO', 'MDE', 'MEX', 'MSY', 'NAS',
       'OAK', 'ORD', 'ORH', 'PAP', 'PBI', 'PDX', 'PHL', 'PHX', 'PIT',
       'PLS', 'POP', 'POS', 'PSE', 'PSP', 'PUJ', 'PVD', 'PWM', 'RDU',
       'RIC', 'RNO', 'ROC', 'RSW', 'SAN', 'SAV', 'SDQ', 'SEA', 'SFO',
       'SJC', 'SJO', 'SJU', 'SLC', 'SMF', 'SNU', 'SRQ', 'STI', 'STT',
       'STX', 'SWF', 'SXM', 'SYR', 'TPA', 'UIO', 'UVF'], dtype=object)

In [12]:
temp1 = np.array(dPoints['FlightDate'])
settingPoints = temp1.tolist()
datePoints = [i.split(' ', 1)[0] for i in settingPoints] #Splits the FlightDate Column to just get the Date
uniqueDatePoints = []
for i in datePoints:
    if i not in uniqueDatePoints: #Finds the unique dates of each of the flights
        uniqueDatePoints.append(i)
print(uniqueDatePoints)

timePoints = [i.split(' ', 1)[1] for i in settingPoints] #Splits the FlightDate Column to just get the Time
uniqueTimePoints = []
for i in timePoints:
    if i not in uniqueTimePoints: #Finds the unique times of each of the flights
        uniqueTimePoints.append(i)
sortedTimePoints = sorted(uniqueTimePoints)
print(sortedTimePoints)

['11/29/2017', '11/30/2017', '12/1/2017', '12/2/2017', '12/3/2017', '12/4/2017', '12/5/2017', '12/6/2017', '12/7/2017', '12/8/2017', '12/9/2017', '12/10/2017', '12/11/2017', '12/12/2017', '12/13/2017', '12/14/2017', '12/15/2017', '12/16/2017', '12/17/2017', '12/18/2017', '12/19/2017', '12/20/2017', '12/21/2017', '12/22/2017', '12/23/2017', '12/24/2017', '12/25/2017', '12/26/2017', '12/27/2017', '12/28/2017', '12/29/2017', '12/30/2017', '12/31/2017', '1/1/2018', '1/2/2018', '1/3/2018', '1/4/2018', '1/5/2018', '1/6/2018', '1/7/2018', '1/8/2018', '1/9/2018', '1/10/2018', '1/11/2018', '1/12/2018', '1/13/2018', '1/14/2018', '1/15/2018', '1/16/2018', '1/17/2018', '1/18/2018', '1/19/2018', '1/20/2018', '1/21/2018', '1/22/2018', '1/23/2018', '1/24/2018', '1/25/2018', '1/26/2018', '1/27/2018', '1/28/2018', '1/29/2018', '1/30/2018', '1/31/2018', '2/1/2018', '2/2/2018', '2/3/2018', '2/4/2018', '2/5/2018', '2/6/2018', '2/7/2018', '2/8/2018', '2/9/2018', '2/10/2018', '2/11/2018', '2/12/2018', '2/13/2018', '2/14/2018', '2/15/2018', '2/16/2018', '2/17/2018', '2/18/2018', '2/19/2018', '2/20/2018', '2/21/2018', '2/22/2018', '2/23/2018', '2/24/2018', '2/25/2018', '2/26/2018', '2/27/2018', '2/28/2018', '3/1/2018', '3/2/2018', '3/3/2018', '3/4/2018', '3/5/2018', '3/6/2018', '3/7/2018', '3/8/2018', '3/9/2018', '3/10/2018', '3/11/2018', '3/12/2018', '3/13/2018', '3/14/2018', '3/15/2018', '3/16/2018', '3/17/2018', '3/18/2018', '3/19/2018', '3/20/2018', '3/21/2018', '3/22/2018', '3/23/2018', '3/24/2018', '3/25/2018', '3/26/2018', '3/27/2018', '3/28/2018', '3/29/2018', '3/30/2018', '3/31/2018']
['0:30', '0:40', '0:49', '0:59', '10:00', '10:01', '10:02', '10:03', '10:04', '10:05', '10:06', '10:07', '10:08', '10:09', '10:10', '10:11', '10:12', '10:13', '10:14', '10:15', '10:16', '10:17', '10:18', '10:19', '10:20', '10:21', '10:22', '10:23', '10:24', '10:25', '10:26', '10:27', '10:28', '10:29', '10:30', '10:31', '10:32', '10:33', '10:34', '10:35', '10:36', '10:37', '10:38', '10:39', '10:40', '10:41', '10:42', '10:43', '10:44', '10:45', '10:46', '10:47', '10:48', '10:49', '10:50', '10:51', '10:52', '10:53', '10:54', '10:55', '10:56', '10:57', '10:58', '10:59', '11:00', '11:01', '11:02', '11:03', '11:04', '11:05', '11:06', '11:07', '11:08', '11:09', '11:10', '11:11', '11:12', '11:13', '11:15', '11:16', '11:17', '11:18', '11:19', '11:20', '11:21', '11:22', '11:23', '11:24', '11:25', '11:26', '11:27', '11:28', '11:29', '11:30', '11:31', '11:32', '11:33', '11:34', '11:35', '11:36', '11:37', '11:38', '11:39', '11:40', '11:41', '11:42', '11:43', '11:44', '11:45', '11:46', '11:47', '11:48', '11:49', '11:50', '11:51', '11:52', '11:53', '11:54', '11:55', '11:56', '11:57', '11:58', '11:59', '12:00', '12:01', '12:02', '12:03', '12:04', '12:05', '12:06', '12:07', '12:08', '12:09', '12:10', '12:11', '12:12', '12:13', '12:14', '12:15', '12:16', '12:17', '12:18', '12:19', '12:20', '12:21', '12:22', '12:23', '12:24', '12:25', '12:26', '12:27', '12:29', '12:30', '12:31', '12:32', '12:33', '12:34', '12:35', '12:36', '12:37', '12:38', '12:39', '12:40', '12:41', '12:42', '12:43', '12:44', '12:45', '12:46', '12:47', '12:48', '12:49', '12:50', '12:51', '12:52', '12:53', '12:54', '12:55', '12:56', '12:57', '12:58', '12:59', '13:00', '13:01', '13:02', '13:03', '13:04', '13:05', '13:06', '13:07', '13:08', '13:09', '13:10', '13:11', '13:12', '13:13', '13:14', '13:15', '13:16', '13:17', '13:18', '13:19', '13:20', '13:21', '13:22', '13:23', '13:24', '13:25', '13:26', '13:27', '13:28', '13:29', '13:30', '13:31', '13:32', '13:33', '13:34', '13:35', '13:36', '13:37', '13:38', '13:39', '13:40', '13:41', '13:42', '13:43', '13:44', '13:45', '13:46', '13:47', '13:48', '13:49', '13:50', '13:51', '13:52', '13:53', '13:54', '13:55', '13:56', '13:57', '13:58', '13:59', '14:00', '14:01', '14:02', '14:03', '14:04', '14:05', '14:06', '14:07', '14:08', '14:09', '14:10', '14:11', '14:12', '14:13', '14:14', '14:15', '14:16', '14:17', '14:18', '14:19', '14:20', '14:21', '14:22', '14:23', '14:24', '14:25', '14:27', '14:28', '14:29', '14:30', '14:31', '14:32', '14:33', '14:34', '14:35', '14:36', '14:37', '14:38', '14:39', '14:40', '14:41', '14:42', '14:43', '14:44', '14:45', '14:46', '14:47', '14:48', '14:49', '14:50', '14:51', '14:52', '14:53', '14:54', '14:55', '14:56', '14:57', '14:58', '14:59', '15:00', '15:01', '15:02', '15:03', '15:04', '15:05', '15:06', '15:07', '15:08', '15:09', '15:10', '15:11', '15:12', '15:14', '15:15', '15:16', '15:17', '15:18', '15:19', '15:20', '15:21', '15:22', '15:23', '15:24', '15:25', '15:26', '15:27', '15:28', '15:29', '15:30', '15:31', '15:32', '15:34', '15:35', '15:36', '15:37', '15:38', '15:39', '15:40', '15:41', '15:42', '15:43', '15:44', '15:45', '15:46', '15:47', '15:48', '15:49', '15:50', '15:51', '15:52', '15:53', '15:54', '15:55', '15:56', '15:57', '15:58', '15:59', '16:00', '16:01', '16:02', '16:03', '16:04', '16:05', '16:06', '16:07', '16:08', '16:09', '16:10', '16:11', '16:12', '16:13', '16:14', '16:15', '16:16', '16:17', '16:18', '16:19', '16:20', '16:21', '16:22', '16:23', '16:24', '16:25', '16:26', '16:27', '16:28', '16:29', '16:30', '16:31', '16:32', '16:34', '16:35', '16:36', '16:38', '16:39', '16:40', '16:41', '16:42', '16:43', '16:44', '16:45', '16:46', '16:47', '16:48', '16:49', '16:50', '16:51', '16:52', '16:53', '16:54', '16:55', '16:56', '16:57', '16:58', '16:59', '17:00', '17:01', '17:02', '17:03', '17:04', '17:05', '17:06', '17:07', '17:08', '17:09', '17:10', '17:11', '17:12', '17:13', '17:14', '17:15', '17:16', '17:17', '17:18', '17:19', '17:20', '17:21', '17:22', '17:23', '17:24', '17:25', '17:27', '17:28', '17:29', '17:30', '17:31', '17:32', '17:33', '17:34', '17:35', '17:36', '17:38', '17:39', '17:40', '17:41', '17:42', '17:43', '17:44', '17:45', '17:46', '17:47', '17:48', '17:49', '17:50', '17:51', '17:52', '17:53', '17:54', '17:55', '17:56', '17:57', '17:58', '17:59', '18:00', '18:01', '18:02', '18:03', '18:04', '18:05', '18:06', '18:07', '18:08', '18:09', '18:10', '18:11', '18:12', '18:13', '18:14', '18:15', '18:16', '18:17', '18:18', '18:19', '18:20', '18:21', '18:22', '18:23', '18:24', '18:25', '18:26', '18:27', '18:28', '18:29', '18:30', '18:31', '18:32', '18:33', '18:34', '18:35', '18:36', '18:37', '18:38', '18:39', '18:40', '18:41', '18:42', '18:43', '18:44', '18:45', '18:46', '18:47', '18:48', '18:49', '18:50', '18:51', '18:52', '18:53', '18:54', '18:55', '18:56', '18:57', '18:58', '18:59', '19:00', '19:01', '19:02', '19:03', '19:04', '19:05', '19:06', '19:07', '19:08', '19:09', '19:10', '19:11', '19:12', '19:13', '19:14', '19:15', '19:16', '19:17', '19:18', '19:19', '19:20', '19:21', '19:23', '19:24', '19:25', '19:26', '19:27', '19:28', '19:29', '19:30', '19:31', '19:32', '19:33', '19:34', '19:35', '19:36', '19:37', '19:38', '19:39', '19:40', '19:41', '19:42', '19:43', '19:44', '19:45', '19:46', '19:47', '19:48', '19:49', '19:50', '19:52', '19:53', '19:54', '19:55', '19:57', '19:58', '19:59', '1:13', '1:25', '1:28', '1:30', '1:40', '1:45', '1:46', '1:52', '1:57', '1:59', '20:00', '20:01', '20:02', '20:03', '20:04', '20:05', '20:06', '20:07', '20:08', '20:09', '20:10', '20:11', '20:12', '20:13', '20:14', '20:15', '20:16', '20:17', '20:18', '20:19', '20:20', '20:21', '20:22', '20:23', '20:24', '20:25', '20:26', '20:27', '20:28', '20:29', '20:30', '20:31', '20:32', '20:33', '20:34', '20:35', '20:36', '20:37', '20:38', '20:39', '20:40', '20:41', '20:42', '20:43', '20:45', '20:46', '20:47', '20:48', '20:49', '20:50', '20:51', '20:52', '20:53', '20:54', '20:55', '20:56', '20:57', '20:58', '20:59', '21:00', '21:01', '21:02', '21:03', '21:04', '21:05', '21:06', '21:07', '21:08', '21:09', '21:10', '21:11', '21:12', '21:13', '21:14', '21:15', '21:16', '21:17', '21:18', '21:19', '21:20', '21:21', '21:22', '21:23', '21:24', '21:25', '21:26', '21:27', '21:28', '21:29', '21:30', '21:31', '21:32', '21:33', '21:34', '21:35', '21:37', '21:38', '21:39', '21:40', '21:41', '21:42', '21:43', '21:44', '21:45', '21:46', '21:47', '21:48', '21:49', '21:50', '21:51', '21:52', '21:54', '21:55', '21:56', '21:57', '21:58', '21:59', '22:00', '22:01', '22:02', '22:03', '22:05', '22:06', '22:07', '22:08', '22:09', '22:10', '22:11', '22:12', '22:13', '22:15', '22:16', '22:17', '22:18', '22:19', '22:20', '22:22', '22:23', '22:24', '22:25', '22:26', '22:27', '22:28', '22:29', '22:30', '22:31', '22:32', '22:33', '22:34', '22:35', '22:36', '22:37', '22:38', '22:39', '22:40', '22:41', '22:42', '22:43', '22:44', '22:45', '22:46', '22:48', '22:49', '22:50', '22:51', '22:52', '22:54', '22:55', '22:56', '22:57', '22:58', '22:59', '23:00', '23:02', '23:05', '23:06', '23:07', '23:08', '23:10', '23:11', '23:12', '23:13', '23:14', '23:15', '23:16', '23:17', '23:18', '23:20', '23:22', '23:23', '23:25', '23:26', '23:27', '23:28', '23:29', '23:30', '23:31', '23:33', '23:35', '23:36', '23:37', '23:38', '23:39', '23:40', '23:41', '23:42', '23:43', '23:44', '23:45', '23:46', '23:48', '23:49', '23:50', '23:51', '23:52', '23:53', '23:54', '23:55', '23:56', '23:57', '23:58', '23:59', '2:09', '2:28', '2:30', '2:32', '2:35', '2:38', '2:39', '2:40', '2:45', '2:46', '2:47', '2:48', '2:50', '2:55', '2:57', '2:58', '3:00', '3:06', '3:07', '3:08', '3:17', '3:20', '3:22', '3:24', '3:26', '3:27', '3:30', '3:31', '3:34', '3:36', '3:38', '3:39', '3:40', '3:41', '3:43', '3:44', '3:48', '4:00', '4:05', '4:06', '4:07', '4:08', '4:11', '4:13', '4:14', '4:15', '4:18', '4:21', '4:24', '4:27', '4:28', '4:30', '4:32', '4:35', '4:36', '4:39', '4:40', '4:41', '4:48', '4:49', '4:51', '4:57', '4:58', '4:59', '5:00', '5:01', '5:02', '5:03', '5:06', '5:07', '5:08', '5:15', '5:18', '5:20', '5:24', '5:25', '5:30', '5:32', '5:33', '5:34', '5:35', '5:36', '5:37', '5:38', '5:39', '5:40', '5:43', '5:45', '5:46', '5:47', '5:50', '5:52', '5:54', '5:57', '5:58', '5:59', '6:00', '6:01', '6:02', '6:03', '6:04', '6:05', '6:06', '6:07', '6:08', '6:09', '6:10', '6:11', '6:12', '6:13', '6:14', '6:15', '6:16', '6:17', '6:18', '6:20', '6:21', '6:22', '6:23', '6:24', '6:25', '6:26', '6:28', '6:29', '6:30', '6:32', '6:33', '6:34', '6:35', '6:36', '6:37', '6:38', '6:39', '6:40', '6:41', '6:43', '6:44', '6:45', '6:46', '6:48', '6:49', '6:50', '6:51', '6:52', '6:53', '6:54', '6:55', '6:56', '6:57', '6:58', '6:59', '7:00', '7:01', '7:02', '7:03', '7:04', '7:05', '7:06', '7:07', '7:08', '7:09', '7:10', '7:11', '7:12', '7:13', '7:14', '7:15', '7:16', '7:17', '7:18', '7:19', '7:20', '7:21', '7:22', '7:23', '7:24', '7:25', '7:26', '7:27', '7:28', '7:29', '7:30', '7:31', '7:32', '7:33', '7:34', '7:35', '7:36', '7:37', '7:38', '7:39', '7:40', '7:41', '7:42', '7:43', '7:44', '7:45', '7:47', '7:48', '7:49', '7:50', '7:51', '7:52', '7:53', '7:54', '7:55', '7:56', '7:57', '7:58', '7:59', '8:00', '8:01', '8:02', '8:03', '8:04', '8:05', '8:06', '8:07', '8:08', '8:09', '8:10', '8:11', '8:12', '8:13', '8:15', '8:16', '8:17', '8:18', '8:19', '8:20', '8:21', '8:22', '8:23', '8:24', '8:25', '8:26', '8:27', '8:28', '8:29', '8:30', '8:31', '8:32', '8:33', '8:34', '8:35', '8:36', '8:37', '8:38', '8:39', '8:40', '8:41', '8:42', '8:43', '8:44', '8:45', '8:46', '8:47', '8:48', '8:49', '8:50', '8:51', '8:52', '8:53', '8:54', '8:55', '8:56', '8:57', '8:58', '8:59', '9:00', '9:01', '9:02', '9:03', '9:04', '9:05', '9:06', '9:07', '9:08', '9:09', '9:10', '9:11', '9:12', '9:13', '9:15', '9:16', '9:17', '9:19', '9:20', '9:21', '9:22', '9:23', '9:24', '9:25', '9:26', '9:27', '9:28', '9:29', '9:30', '9:31', '9:32', '9:33', '9:34', '9:35', '9:36', '9:38', '9:39', '9:40', '9:41', '9:42', '9:43', '9:44', '9:45', '9:46', '9:47', '9:48', '9:49', '9:50', '9:51', '9:52', '9:53', '9:54', '9:55', '9:56', '9:57', '9:58', '9:59']

In [13]:
amountPoints = np.array(dPoints['TotalAmount'])
sortedPoints = np.sort(amountPoints) #Sorts data set by the total cost of the flight, cheapest to most expensive
print(sortedPoints)

[   46.59    46.59    46.59 ...,  1445.32  1491.32  1541.12]